### ISSUE TITLE
mapped-databases set to [] on server restart if no initial value provided

### ISSUE THREAD

**Issue by massdosage** [HotelsDotCom/waggle-dance#82]
Reported by an internal user, I'm guessing this is the sequence of events that causes a bug:

1. Create a federation yml file and for the "federated-meta-stores" completely omit the "mapped-databases" and "overwrite-config-on-shutdown" configuration so these get their default values.
2. Start and then stop Waggle Dance.
3. Check the configuration file, if the issue is reproduced then "mapped-databases" will now be in the config file and set to [] which now means *no* databases are being federated (instead of the default of all of them).

To fix this we need to ensure that if no mapped databases have been configured that the update of the config file on shutdown doesn't put an empty list into the file.

**Comment by patduin** [comment]
Is this PREFIXED or MANUAL mode?

**Comment by massdosage** [comment]
This is the example yaml file after it had been rewritten, so yes, it's in PREFIXED mode:

primary-meta-store:
```
  access-control-type: READ_ONLY
  database-prefix: ''
  name: local
  remote-meta-store-uris: thrift://localhost:9083
federated-meta-stores:
- access-control-type: READ_ONLY
  database-prefix: dw_
  mapped-databases: []
  name: dw
  remote-meta-store-uris: thrift://XXX.internal:9083
```
